### ISSUE TITLE
Revisit error model

### ISSUE THREAD

**Issue by vitaliihonta** [vitaliihonta/zio-temporal#33]
Either's are not retried by temporal. Only thrown exceptions are.
The only way ZIO errors can be retried is using ZIO.die, which looks strange

Here is a list of examples to verify the new zio-temporal error model on:
- [x] https://gist.github.com/carlosedp/61703d5c436dc50ec5876249fbbbed31
- [x] Check how it works with ZSaga's
- [x] Try providing better client errors instead of just TemporalClientError and TemporalBusinessError
- [x] Update documentation

**Comment by carlosedp** [comment]
It's weird to have only ZIO.die trigger retries since ZIO will throw an error and kill the fiber generating an stack trace. I understand the retry mechanic could be part of the logic to better handle errors.

In the Java SDK, you can even filter which exceptions are filtered-out and I believe it's a good model: https://github.com/temporalio/samples-java/blob/cb78ebce84f7f3346bc0584282a34d06b21181f2/src/main/java/io/temporal/samples/hello/HelloActivityRetry.java#L110.

This way we could have retries on exceptions (whenever you return a ZIO failure but could also filter ones that should not.

**Comment by vitaliihonta** [comment]
@oridag  I've finally managed to release the new error model, feel free to try it out!
I appreciate any feedback 😄

**Comment by oridag** [comment]
Nice! I'll be sure to give it a try soon!
